# Generated by Django 5.1 on 2024-10-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_pledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='supporter',
        ),
    ]
